name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Docker image name'
        required: true
        type: choice
        options:
          - 'missaelcorm/schedulesync-api'
          - 'missaelcorm/schedulesync-web'
      docker_tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'
      deploy-k8s:
        type: boolean
        description: 'Deploy to Kubernetes'
        required: true
        default: false

permissions:
  contents: read
  security-events: write

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env: 
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
      DOCKER_TAG: ${{ github.event.inputs.docker_tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set Docker Context
      run: |
        if [ "${{ env.DOCKER_IMAGE }}" == "missaelcorm/schedulesync-api" ]; then
          echo "DOCKER_LOCAL_CONTEXT=backend" >> $GITHUB_ENV
        elif [ "${{ env.DOCKER_IMAGE }}" == "missaelcorm/schedulesync-web" ]; then
          echo "DOCKER_LOCAL_CONTEXT=frontend" >> $GITHUB_ENV
        fi

    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: ./${{ env.DOCKER_LOCAL_CONTEXT }}
        file: ./${{ env.DOCKER_LOCAL_CONTEXT }}/Dockerfile
        push: true
        tags: "${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}"

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      env:
        TRIVY_DB_REPOSITORY: 'public.ecr.aws/aquasecurity/trivy-db:2'
      with:
        image-ref: '${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}'
        format: 'json'
        output: 'trivy-results.json'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'
      continue-on-error: true

    - name: Upload Trivy scan results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-trivy-schedulesync-json-${{ github.sha }}
        path: trivy-results.json

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript'

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: 'codeql-${{ github.event.inputs.docker_image }}'
        output: 'codeql-results.sarif' # Explicit output for CodeQL

    - name: Upload CodeQL Results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: security-codeql-schedulesync-sarif-${{ github.sha }}
        path: codeql-results.sarif
        if-no-files-found: warn

  trigger_deploy:
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy-k8s == true
    needs: [build_and_push]
    env:
      DOCKER_IMAGE: ${{ github.event.inputs.docker_image }}
      DOCKER_TAG: ${{ github.event.inputs.docker_tag }}
      WORKFLOW_NAME: 'deploy-schedulesync-api'
    steps:
    - name: Trigger CD Pipeline at ${{ vars.SCHEDULESYNC_DEVOPS_REPO }} repo
      run: |
        curl -X POST https://api.github.com/repos/${{ vars.SCHEDULESYNC_DEVOPS_REPO }}/dispatches \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.PAT_GA_SCHEDULESYNC_DEVOPS }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        --data '{"event_type": "${{ env.WORKFLOW_NAME }}", "client_payload": { "repository": "${{ env.GITHUB_REPOSITORY }}", "docker_tag": "${{ env.DOCKER_TAG }}", "docker_image": "${{ env.DOCKER_IMAGE }}" }}'

  notify_slack:
    runs-on: ubuntu-latest
    needs: [build_and_push, trigger_deploy]
    if: ${{ always() }}
    steps:
    - name: Send notification to Slack
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_CHANNEL: '#notifications' # Canal de Slack
        SLACK_USERNAME: 'CI Bot'
        SLACK_MSG_AUTHOR: ${{ github.actor }}
        SLACK_ICON_EMOJI: ':rocket:' # Emoji personalizado
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: 'CI/CD Pipeline Notification'
        SLACK_FOOTER: 'Powered by GitHub Actions'
        SLACK_MESSAGE: |
          Pipeline for job `${{ github.job }}` in repository `${{ github.repository }}` completed.
          - Ref: `${{ github.ref }}`
          - Commit Message: `${{ github.event.head_commit.message }}`
          - Committer: `${{ github.event.head_commit.committer.name }}`

