name: Test GA

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Write some test'
        required: true
        default: 'Hello World'

jobs:     
  print_text:
    runs-on: [ubuntu-latest]
    container: "python:3.9-alpine3.19"
    env: 
      SCHEDULESYNC_API_DIR: "backend/"
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Print SCHEDULESYNC_API_DIR
      run: |
        echo "Backend is at: ${{ env.SCHEDULESYNC_API_DIR }}"
      
    - name: Print input text
      run: |
        echo "Input text: ${{ github.event.inputs.text }}"

    - name: Print python version
      run: |
        python --version
